." +AMDG
." Process with:
." groff -man -Tascii doman.1
.TH doman 1 "January 2010" Linux "User Manuals"
.SH NAME
doman \- convert dozenal integers to arbitrary non-place-value systems
.SH SYNOPSIS
.B doman [-R 
.I dozenal integer
.B ] [-r
.I ranks
.B ] [-s
.I symbols
.B ]
.SH DESCRIPTION
.B doman
converts dozenal integers to arbitrary non-place-value
systems.  Only accept dozenal integers as input; fractional
places will be silently truncated.  Can accept arbitrary
symbols; e.g., to duplicate Roman numerals, use 
\fB-s"M,D,C,L,X,V,I" -r"6E4,358,84,42,X,5,1"\fR.  Any character
or string of characters may be used as a symbol.
.SH OPTIONS
.TP
.BR "-R integer"
The number you wish \fBdoman\fR to convert.
.TP
.BR "-r ranks"
Takes as a comma-separated list the ranks you wish to use
for assembling the non-place-value number.  E.g., for Roman
numerals, you'd use "6E4,358,84,42,X,5,1", those being
the numbers that have separate symbols in Roman numerals.
You can have as many or as few of these as you wish.
.PP
.RS
Notice that this is a comma-separated list of \fIdozenal\fR
values; decimal values will be interpreted as dozenal,
which, if you meant to use decimal values, will not give you
the result you want.
.PP
Note that there must be the same number of ranks as symbols;
if there isn't, \fBdoman\fR will emit an error and die.
.RE
.TP
.BR "-s symbols"
Takes as a comma-separated list the symbols you wish to use
for each rank.  E.g., for Roman numerals, you'd use
"M,D,C,L,X,V,I".  However, any symbols can be used, of
whatever length; multi-byte characters (or multiple
characters) are fine.
.PP
.RS
Note that there must be the same number of ranks as symbols;
if there isn't, \fBdoman\fR will emit an error and die.
.RE
.SH BUGS
.SH AUTHOR
Donald P. Goodman III <dgoodmaniii at gmail dot com>
.SH "SEE ALSO"
.BR dec (1),
.BR dozdc (1),
.BR tgmconv (1),
.BR dozdate (1),
.BR dozcal (1),
.BR dozword (1),
.BR dozpret (1)
