." +AMDG
." Process with:
." groff -man -Tascii dozword.1
.TH dozword 1 "January 2010" Linux "User Manuals"
.SH NAME
dozword \- convert dozenal integers into words
.SH SYNOPSIS
.B dozword [ -p -s -n
.I decimal number
.B ]
.SH DESCRIPTION
.B dozword
converts a dozenal integer, such as "X44", into words, such
as "Ten biqua four four", according to either System Dozenal
Nomenclature (SDN) or the Pendlebury system.  Fractional
parts are ignored, because they are totally uninteresting
(they can be pronounced simply, for example, "dit four seven
nine elv").
.PP
If the number of digits in the number exceeds EE EEEE,
\fBdozword\fR will silently truncate that number, and thus
incorrectly print its output.  Thus, the answer will be
incorrect.  Otherwise, however, very large
integers won't ruin the program, and beneath this limit, any
integer will be correctly output.
.SH OPTIONS
.TP
.BR \-s
Use the System Dozenal Nomenclature (SDN) system for the
power words.  This is the default; you don't need to specify
this option if you don't want.
.TP
.BR \-p
Use the Pendlebury system for the power words.
.TP
.BR "\-n \fInumber\fR"
Takes as an argument the number you wish to convert.  Useful
if you don't want to take your data from standard input.
.SH BUGS
None known at this time.
.SH AUTHOR
Donald P. Goodman III <dgoodmaniii at gmail dot com>
.SH "SEE ALSO"
.BR dec (1),
.BR dozdc (1),
.BR tgmconv (1),
.BR dozdate (1),
.BR dozcal (1),
.BR dozword (1),
.BR dozpret (1)
