/* Form definition file generated by fdesign on Sun Sep 25 20:59:07 2016 */

#include <stdlib.h>
#include "dozbc.h"



/***************************************
 ***************************************/

FD_calculator *
create_form_calculator( void )
{
    FL_OBJECT *obj;
    FD_calculator *fdui = ( FD_calculator * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->calculator = fl_bgn_form( FL_NO_BOX, 562, 250 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 562, 250, "" );

    fdui->dit = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 50, 40, 40, ";" );
    fl_set_button_shortcut( obj, ";", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, ';' );

    fdui->neg = obj = fl_add_button( FL_NORMAL_BUTTON, 30, 50, 40, 40, "+/-" );
    fl_set_button_shortcut( obj, "n", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '-' );

    fdui->nine = obj = fl_add_button( FL_NORMAL_BUTTON, 30, 90, 40, 40, "9" );
    fl_set_button_shortcut( obj, "9", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '9' );

    fdui->ten = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 90, 40, 40, "X" );
    fl_set_button_shortcut( obj, "x", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, 'X' );

    fdui->six = obj = fl_add_button( FL_NORMAL_BUTTON, 30, 130, 40, 40, "6" );
    fl_set_button_shortcut( obj, "6", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '6' );

    fdui->seven = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 130, 40, 40, "7" );
    fl_set_button_shortcut( obj, "7", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '7' );

    fdui->three = obj = fl_add_button( FL_NORMAL_BUTTON, 30, 170, 40, 40, "3" );
    fl_set_button_shortcut( obj, "3", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '3' );

    fdui->four = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 170, 40, 40, "4" );
    fl_set_button_shortcut( obj, "4", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '4' );

    fdui->zero = obj = fl_add_button( FL_NORMAL_BUTTON, 30, 210, 40, 40, "0" );
    fl_set_button_shortcut( obj, "0", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '0' );

    fdui->one = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 210, 40, 40, "1" );
    fl_set_button_shortcut( obj, "1", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '1' );

    fdui->two = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 210, 40, 40, "2" );
    fl_set_button_shortcut( obj, "2", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '2' );

    fdui->five = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 170, 40, 40, "5" );
    fl_set_button_shortcut( obj, "5", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '5' );

    fdui->eight = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 130, 40, 40, "8" );
    fl_set_button_shortcut( obj, "8", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, '8' );

    fdui->elv = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 90, 40, 40, "E" );
    fl_set_button_shortcut( obj, "e", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, 'E' );

    fdui->exp = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 50, 40, 40, "e" );
    fl_set_button_shortcut( obj, "E", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, 'e' );

    fdui->div = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 50, 40, 40, "/" );
    fl_set_button_shortcut( obj, "/", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '/' );

    fdui->times = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 90, 40, 40, "*" );
    fl_set_button_shortcut( obj, "*", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '*' );

    fdui->minus = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 130, 40, 40, "-" );
    fl_set_button_shortcut( obj, "-", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '-' );

    fdui->plus = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 170, 40, 40, "+" );
    fl_set_button_shortcut( obj, "+", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '+' );

    fdui->equals = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 210, 40, 40, "=" );
    fl_set_button_shortcut( obj, "=", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '=' );

    fdui->sqrt = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 210, 40, 40, "sqrt" );
    fl_set_button_shortcut( obj, "v", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'v' );

    fdui->expon = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 170, 40, 40, "Exp" );
    fl_set_button_shortcut( obj, "^^", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '^' );

    fdui->closeparen = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 130, 40, 40, ")" );
    fl_set_button_shortcut( obj, ")", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, grouping, ')' );

    fdui->openparen = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 90, 40, 40, "(" );
    fl_set_button_shortcut( obj, "(", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, grouping, '(' );

    fdui->mod = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 50, 40, 40, "%" );
    fl_set_button_shortcut( obj, "%", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '%' );

    fdui->sin = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 50, 40, 40, "sin" );
    fl_set_button_shortcut( obj, "s", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 's' );

    fdui->cosine = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 90, 40, 40, "cos" );
    fl_set_button_shortcut( obj, "c", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'c' );

    fdui->tangent = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 130, 40, 40, "tan" );
    fl_set_button_shortcut( obj, "t", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 't' );

    fdui->dozlog = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 170, 40, 40, "log" );
    fl_set_button_shortcut( obj, "l", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'l' );

    fdui->declog = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 210, 40, 40, "logx" );
    fl_set_button_shortcut( obj, "d", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'x' );

    fdui->natlog = obj = fl_add_button( FL_NORMAL_BUTTON, 270, 210, 40, 40, "nl" );
    fl_set_button_shortcut( obj, "n", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'n' );

    fdui->baselog = obj = fl_add_button( FL_NORMAL_BUTTON, 270, 170, 40, 40, "logb" );
    fl_set_button_shortcut( obj, "b", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'b' );

    fdui->atan = obj = fl_add_button( FL_NORMAL_BUTTON, 270, 130, 40, 40, "atan" );
    fl_set_button_shortcut( obj, "T", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'T' );

    fdui->acos = obj = fl_add_button( FL_NORMAL_BUTTON, 270, 90, 40, 40, "acos" );
    fl_set_button_shortcut( obj, "C", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'C' );

    fdui->asin = obj = fl_add_button( FL_NORMAL_BUTTON, 270, 50, 40, 40, "asin" );
    fl_set_button_shortcut( obj, "S", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'S' );

    fdui->recip = obj = fl_add_button( FL_NORMAL_BUTTON, 310, 210, 40, 40, "1/x" );
    fl_set_button_shortcut( obj, "r", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'r' );

    fdui->dublog = obj = fl_add_button( FL_NORMAL_BUTTON, 310, 170, 40, 40, "dlg" );
    fl_set_button_shortcut( obj, "D", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'D' );

    fdui->hytan = obj = fl_add_button( FL_NORMAL_BUTTON, 310, 130, 40, 40, "tanh" );
    fl_set_button_shortcut( obj, "y", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'y' );

    fdui->hycos = obj = fl_add_button( FL_NORMAL_BUTTON, 310, 90, 40, 40, "cosh" );
    fl_set_button_shortcut( obj, "H", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'H' );

    fdui->hysin = obj = fl_add_button( FL_NORMAL_BUTTON, 310, 50, 40, 40, "sinh" );
    fl_set_button_shortcut( obj, "h", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'h' );

    fdui->clear = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 50, 40, 40, "Cl" );
    fl_set_button_shortcut( obj, "w", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, erase, 'c' );

    fdui->backspace = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 90, 40, 40, "<-" );
    fl_set_button_shortcut( obj, "<", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, erase, '<' );

    fdui->factorial = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 130, 40, 40, "!" );
    fl_set_button_shortcut( obj, "!", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, '!' );

    fdui->pi = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 170, 40, 40, "pi" );
    fl_set_button_shortcut( obj, "p", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, proc_num, 'p' );

    fdui->euler = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 210, 40, 40, "e" );
    fl_set_button_shortcut( obj, "u", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLDITALIC_STYLE );
    fl_set_object_callback( obj, proc_num, 'u' );

    fdui->angleunit = obj = fl_add_button( FL_NORMAL_BUTTON, 430, 210, 40, 40, "z/r/d" );
    fl_set_button_shortcut( obj, "z", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, unitangle, 0 );

    fdui->memappend = obj = fl_add_button( FL_NORMAL_BUTTON, 430, 90, 40, 40, "M++" );
    fl_set_button_shortcut( obj, "A", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, memory, 'A' );

    fdui->memadd = obj = fl_add_button( FL_NORMAL_BUTTON, 430, 50, 40, 40, "M+" );
    fl_set_button_shortcut( obj, "a", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, memory, '+' );

    fdui->ansfield = obj = fl_add_text( FL_NORMAL_TEXT, 70, 16, 400, 34, "" );
    fl_set_object_boxtype( obj, FL_DOWN_BOX );
    fl_set_object_color( obj, FL_ALICEBLUE, FL_BLACK );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );

    fdui->angletype = obj = fl_add_text( FL_NORMAL_TEXT, 34, 20, 35, 26, "" );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );

    fdui->greatcommfact = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 50, 40, 40, "gcf" );
    fl_set_button_shortcut( obj, "g", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'g' );

    fdui->leastcommult = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 90, 40, 40, "lcm" );
    fl_set_button_shortcut( obj, "L", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 'L' );

    obj = fl_add_button( FL_NORMAL_BUTTON, 390, 130, 40, 40, "" );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 390, 170, 40, 40, "" );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, 0 );

    fdui->comma = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 210, 40, 40, "," );
    fl_set_button_shortcut( obj, ",", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, operator, ',' );

    fdui->memrep = obj = fl_add_button( FL_NORMAL_BUTTON, 430, 130, 40, 40, "M" );
    fl_set_button_shortcut( obj, "R", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, memory, 'r' );

    fdui->clearmem = obj = fl_add_button( FL_NORMAL_BUTTON, 430, 170, 40, 40, "CM" );
    fl_set_button_shortcut( obj, "k", 1 );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, memory, 'c' );

    fdui->precisionval = obj = fl_add_spinner( FL_INT_SPINNER, 33, 18, 37, 32, "" );
    fl_set_object_lstyle( obj, FL_TIMESBOLD_STYLE );
    fl_set_object_callback( obj, set_prec, 0 );
    fl_set_spinner_bounds( obj, 0, 15 );
    fl_set_spinner_value( obj, 4 );
    fl_set_object_lstyle( fl_get_spinner_input( obj ), FL_TIMESBOLD_STYLE );

    fl_end_form( );

    fdui->calculator->fdui = fdui;

    return fdui;
}
