." +AMDG
." Process with:
." groff -man -Tascii dozcal.1
.TH dozcal 1 "August 2016" dgoodmaniii dozcal
.SH NAME
dozcal \- a command-line dozenal calendar program
.SH SYNOPSIS
.B dozcal
[\fB\-V\fR]
[\fB\-m\fR \fIfull|major\fR]
[\fB\-h\fR \fIreligious\fR]
[\fB\-s\fR \fIstartdate\fR]
[\fB\-e\fR \fIenddate\fR]
[\fB\-d\fR \fIdateformat\fR]
[\fB\-t\fR \fItimeformat\fR]
[\fB\-r\fR \fIeventformat\fR]
[\fB\-c\fR \fIconfigfile\fR]
[\fB\-f\fR \fIinputfile\fR]
.SH DESCRIPTION
.B dozcal
A text-based calendar program which operates using dozenal
dates and times.  Uses a simple plain-text file format.
Multiple files can be specified on the command line.  Date
formats and time formats can also be specified on the
command line.  All can further be specified in a
configuration file, which is also plain-text and easily
understandable.
.SH OPTIONS
.TP
.BR \-V
Print version and licensing information, then exit
successfully.
.TP
.BR \-m
Include the phases of the moon in your output.  This must
take one of two arguments:  "all", which will print the
phase of the moon for all days in your date range; or
"major", which will only print the major phases (i.e.,
"new", "first quarter", "full", and "last quarter").  In
either case, the age of the moon in days is printed as its
phase, which some text for the major phases.
.TP
.BR \-h
Include religious holidays.  This takes a single string as
an argument, and the contents of the string determine which
holidays will be added.  The holidays are added for the year
before your current year, the current year, and the year
after.
.RS
.TP
.BR west
Include Western Christian holidays.  This includes a subset
of Western Christian holidays:  Ash Wednesday, Palm Sunday,
Good Friday, Easter, the Ascension, Pentecost, and
Christmas.
.TP
.BR east
Include Eastern Christian holidays.  This includes a subset
of Eastern Christian holidays:  Clean Monday, Lazarus
Saturday, Palm Sunday, Easter, Mid-Pentecost, the Ascension,
Pentecost, and Christmas.
.TP
.BR jew
Include Jewish holidays.  This setting ignores some of the
prickier issues of the Hebrew calendar, including those
holidays which sometimes fall in the leap month.  Includes
Passover; Yom Kippur; Rosh Hashanah; Hanukkah; and Sukkot.
.TP
.BR isl
Include Islamic holidays.  It's important to remember that
the Islamic calendar is fundamentally observational, not
mathematical; it's therefore impossible to get a perfectly
accurate prediction of when these holidays will occur.  We
can get pretty close, though, and \fBdozcal\fR gets an
approximation that agrees more or less with the other
sources around (which often read "dates may vary" for
precisely this reason).  Includes Ramadan, Eid Al-Fitr, and
Eid Al-Adha.
.RE
.TP
.BR \-n
Include national holidays in your results.  Supported
national holidays are the United States ("usa"), the United
Kingdom ("uk"), England ("eng"), Scotland ("scot"), Wales
("wales"), Northern Ireland ("nire"), the Republic of
Ireland ("rire"), Australia ("austral"), and New Zealand
("nz" or "kiwi").
.RS
.TP
.BR usa
Includes all federal American holidays:  New Year's Day,
Martin Luther King Day, Presidents' Day (officially still
called "Washington's Birthday", though it never actually
falls on Washington's birthday), Memorial Day, Independence
Day, Labor Day, Columbus Day, Veterans Day, Thanksgiving
Day, and Christmas Day.  It also includes election day,
though this is not a federal holiday.
.RE
.TP
.BR \-s
The first date that you want results from.  If this is not
specified, \fBdozcal\fR will return all results from its earliest
date.
.TP
.BR \-e
The last date that you want results from.  Combined with
\fB\-s\fR, you can restrict the range of results you'll
receive.  If this isn't specified, \fBdozcal\fR will return
results from the start date until it runs out.
.TP
.BR \-d
The date format.  These are specified identically to those
of the standard Unix \fBdate\fR command; please see the
documentation for that for more details.  (Note that this
does \fInot\fR include the \fBdozdate\fR extensions,
beginning with \fI@\fR rather than \fI%\fR; they're not
necessary for this problem domain.)
.TP
.BR \-t
The time format.  Much simpler than date format,
\fBdozcal\fR assumes the use of hours and Tims for time, and
doesn't support anything else at this time.  Only two
interpreted sequences are allowed:
.RS
.TP 
.BR %h
The hours.
.TP
.BR %b
Tims.  These are the number of Tims in an hour, so they cap
off at EEEE.  \fBdozcal\fR will happily display these to
less than 4 digits, if requested.
.RE
.TP
.BR \-r
The event format.  Each event in your calendar is printed as
a separate record; the argument to this option allows you to
specify its format.  It operates independently of \fB\-d\fR
and \fB\-t\fR, which will still be formatted as you request.
It accepts the following conversion strings:
.RS
.TP 
.BR %e
The event title.
.TP
.BR %d
The event date, formatted as you requested if you've given
\fBdozcal\fR a date formatting string.
.TP
.BR %s
The event's starting time, formatted as you requested if
you've given \fBdozcal\fR a time formatting string.
.TP
.BR %c
The event's closing (ending) time, formatted as you requested if
you've given \fBdozcal\fR a time formatting string.
.RE
.SH FILES
\fBdozcal\fR uses two files primarily:  the data, or library
file, which has the actual library information in it, and a
run-control, or config file, which contains simple lines to
control \fBminlib\fR's behavior.
.SS The Data File
.PP
\fBdozcal\fR works with data files that follow a simple but
specific format.  Each record begins with a line containing
the string \fI[EVENT]\fR and ends either at the end of the
file or at the next line containing \fI[EVENT]\fR; blank
lines are ignored.
.PP
Within each event, you must specify at least a \fITITLE\fR
and a \fISTART_DATE\fR.  The following are recognized
fields:
.RS
.TP
.BR TITLE:
Gives the title of the event; e.g., "Meeting with Roy" or
"Traffic Court".
.TP
.BR START_DATE:
The date on which the event occurs.  It is called start-date
because many events recur on the calendar, but this one
serves as either the only event or the first of a recurring
event.
.TP
.BR END_DATE:
The last date of the event, and (if you've specified an
\fIINTERVAL\fR for this event) the last day that
\fBdozcal\fR will check to see if a recurrence should occur.
.TP
.BR INTERVAL:
The number of days' interval for a recurring date.  That is,
starting at the \fISTART_DATE\fR, how many days should
\fBdozcal\fR skip before placing the event on the calendar
again?  To make a weekly event, for example, say
\fIINTERVAL:  7\fR.  If you say \fIINTERVAL:  1\fR, the
event will occur every day (in which case, you may as well
not specify an interval, because \fBdozcal\fR will assume
you mean every day until the \fIEND_DATE\fR unless you tell
it otherwise).
.TP
.BR EXCEPT_DATE:
In a recurring event, \fIdon't\fR add an event on this date,
even if it otherwise qualifies.  You can have as many of
these as you'd like.
.TP
.BR START_TIME:
The time you'd like this to start.  This can be specified in
either our normal dozenal-sexagesimal time (two dozen hours
in a day, five dozen minutes in an hour), or in TGM (two
dozen hours in a day, divided into 10000 Tims each).
\fBdozcal\fR will interpret the time as dozenal-sexagesimal
if you use a colon (\fI:\fR) to separate the hours from
minutes; if you use a semicolon (\fI;\fR), or no
punctuation, it will interpret the time as hours and Tims.
.TP
.BR END_TIME:
The obvious corrollary of \fISTART_TIME\fR.
.RE
.PP
An example record:
.RS
[EVENT]
.br
START_DATE:  1200-0X-27
.br
END_DATE:  1200-0E-0X
.br
START_TIME:  0X00
.br
END_TIME:  1E30
.br
EXCEPT_DATE:  1200-0E-04
.br
EXCEPT_DATE:  1200-0E-05
.br
TITLE:  My Test Event #1
.RE
.SH ERRORS
.PP
\fBdozcal\fR emits fairly specific error codes when things
go wrong.  Successful completion is returned to the
environment as \fI0\fR.
.TP
.BR 1
You supplied \fBdozcal\fR an option which requires an
argument, but didn't send it an argument.  E.g., you said
\fB\-s\fR, but didn't say what you wanted the starting date
of your results to be.
.TP
.BR 2
You gave \fBdozcal\fR an option that it doesn't recognize.
.TP
.BR 3
There's insufficient memory for somethinng that \fBdozcal\fR
needs to do; see the error message emitted to see what
exactly it was.
.TP
.BR 4
\fBdozcal\fR is trying to open a file you gave it (perhaps
with \fB\-f\fR or \fB\-c\fR), but is running into problems.
\fBdozcal\fR will print an error message detailing the
specific error.
.TP
.BR 5
You've given a conversion character in your time format
(perhaps with the \fB\-t\fR option) that \fBdozcal\fR
doesn't recognize.
.TP
.BR 6
You've given a conversion character in your event format
(perhaps with the \fB\-r\fR option) that \fBdozcal\fR
doesn't recognize.
.SH BUGS
None known at this time.
.SH AUTHOR
Donald P. Goodman III <dgoodmaniii at gmail dot com>
.SH SEE ALSO
pdfinfo
